### ISSUE TITLE
Exception on HAL serialization with object mapper configured to sort map entries by keys

### ISSUE THREAD

**Issue by frank256** [spring-projects/spring-hateoas#1515]
This concerns JSON HAL serialization using Spring Boot 2.4.4 / Spring HATEOAS 1.2.5.

When using an object mapper which has the feature `SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS` enabled (which is, unfortunately, mandatory for me in a legacy project), I will get an `HttpMessageNotWritableException` due to a `JsonMappingException` with the cause being that `org.springframework.hateoas.mediatype.hal.HalLinkRelation` cannot be cast to `java.lang.Comparable`.
This is due to the Jackson MapSerializer being used to serialize the links, which expects the map keys to be comparable if the feature is enabled. However, HalLinkRelation does not implement `Comparable` nor is the map (I understand the links are already sorted?) that is passed into it implementing `SortedMap` (this is checked).

I tried to customize the object mapper with a custom map serializer that adds the links to a temporary TreeMap so that they are not sorted again by the MapSerializer, however, as the map serializer is constructed directly within the Jackson2HalModule (lines 202-5), I currently do not see how I can intervene here.

I'd consider this more or less a bug (?), however, if you have a hint for a workaround, I'd also appreciate that very much!

Disabling the feature is, unfortunately, not an option for me. It worked with Spring HATEOAS before 1.0.0.

**Comment by odrotbohm** [comment]
Can you provide an example that's reproducing the error? I think we should be able to work around this Jackson limitation by mapping the `LinkRelation` keys to their `String` representation.

**Comment by frank256** [comment]
Thanks for the fast reply! I cannot attach code from the original project, so I tried to prepare a very minimal demo using Spring Data Rest. Of course, there would not be any meaningful sorting taking place here. But you can see the exception.

The original project also makes heavy use of custom RepresentationModels, RepresentationModelProcessors and other HATEOAS functionality not related to Spring Data Rest. 

[spring-hateoas-hal-map-sort-demo.zip](https://github.com/spring-projects/spring-hateoas/files/6306712/spring-hateoas-hal-map-sort-demo.zip)

**Comment by odrotbohm** [comment]
Actually, it should be reproducible using an `ObjectMapper` with the HAL customizations registered and the serialization settings tweaked to what you described. I'll have a look at your sample and see where I can take this.

**Comment by odrotbohm** [comment]
This is in place for 1.4, 1.3 and 1.2 snapshots. Feel free to give it a spin.

**Comment by frank256** [comment]
Thank you very much!

Tried the 1.2.6 snapshot today. Unfortunately, there is still an exception of the same type thrown when rendering embedded collections (via line 338 of Jackson2HalModule). Sorry, I did not catch this one when analyzing it at first.  

Stack trace:
```
Caused by: java.lang.ClassCastException: class org.springframework.hateoas.mediatype.hal.HalLinkRelation cannot be cast to class java.lang.Comparable (org.springframework.hateoas.mediatype.hal.HalLinkRelation is in unnamed module of loader 'app'; java.lang.Comparable is in module java.base of loader 'bootstrap')
	at java.base/java.util.TreeMap.compare(TreeMap.java:1291) ~[na:na]
	at java.base/java.util.TreeMap.put(TreeMap.java:536) ~[na:na]
	at java.base/java.util.AbstractMap.putAll(AbstractMap.java:281) ~[na:na]
	at java.base/java.util.TreeMap.putAll(TreeMap.java:325) ~[na:na]
	at java.base/java.util.TreeMap.<init>(TreeMap.java:185) ~[na:na]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer._orderEntries(MapSerializer.java:1092) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:671) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:637) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33) ~[jackson-databind-2.11.4.jar:2.11.4]
	at org.springframework.hateoas.mediatype.hal.Jackson2HalModule$HalResourcesSerializer.serialize(Jackson2HalModule.java:338) ~[spring-hateoas-1.2.6-20210416.141502-3.jar:1.2.6-SNAPSHOT]
	at org.springframework.hateoas.mediatype.hal.Jackson2HalModule$HalResourcesSerializer.serialize(Jackson2HalModule.java:290) ~[spring-hateoas-1.2.6-20210416.141502-3.jar:1.2.6-SNAPSHOT]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755) ~[jackson-databind-2.11.4.jar:2.11.4]
```

**Comment by frank256** [comment]
@odrotbohm Ping, since I'm not sure whether you see this. : )

**Comment by odrotbohm** [comment]
I get notified by GitHub, thanks 🙃.

**Comment by odrotbohm** [comment]
Fixes pushed for that. Would be cool if you could take the snapshots for another spin.

**Comment by frank256** [comment]
Tried the new snapshot. Everything seems to work now. 
Awesome! Thank you! :+1:
